#!/usr/bin/env python3
"""Regenerate emojiData.js from Unicode + CLDR source data.

Inputs (downloaded into this directory, not committed):
  emoji-test.txt              https://unicode.org/Public/emoji/15.1/emoji-test.txt
  cldr-annotations-en.xml     cldr release-45 common/annotations/en.xml
  cldr-annotationsDerived-en.xml   cldr release-45 common/annotationsDerived/en.xml

Emoji 15.1 is pinned deliberately: it matches fonts-noto-color-emoji 2.047 as
shipped on Ubuntu 24.04. Bundling a newer set renders unsupported glyphs as
empty boxes.
"""

import collections
import json
import re
import xml.etree.ElementTree as ET
from pathlib import Path

HERE = Path(__file__).parent
OUT = HERE.parent / "emojiData.js"

ICONS = {
    'Smileys & Emotion': 'face-smile-symbolic',
    'People & Body': 'people-symbolic',
    'Animals & Nature': 'pet-symbolic',
    'Food & Drink': 'food-symbolic',
    'Travel & Places': 'airplane-mode-symbolic',
    'Activities': 'applications-games-symbolic',
    'Objects': 'applications-utilities-symbolic',
    'Symbols': 'emoji-symbols-symbolic',
    'Flags': 'flag-outline-thick-symbolic',
}
SHORT = {
    'Smileys & Emotion': 'Smileys', 'People & Body': 'People',
    'Animals & Nature': 'Nature', 'Food & Drink': 'Food',
    'Travel & Places': 'Travel', 'Activities': 'Activities',
    'Objects': 'Objects', 'Symbols': 'Symbols', 'Flags': 'Flags',
}
SKIN_TONES = '\U0001F3FB\U0001F3FC\U0001F3FD\U0001F3FE\U0001F3FF'
LINE_RE = re.compile(r'^([0-9A-Fa-f ]+);\s*(\S+)\s*#\s*(\S+)\s+E[\d.]+\s+(.*)$')


def load_keywords():
    """cp -> set of CLDR synonym words."""
    kw = {}
    for name in ('cldr-annotations-en.xml', 'cldr-annotationsDerived-en.xml'):
        root = ET.parse(HERE / name).getroot()
        for ann in root.iter('annotation'):
            if ann.get('type') == 'tts' or not ann.text:
                continue
            kw.setdefault(ann.get('cp'), set()).update(
                w.strip().lower() for w in ann.text.split('|') if w.strip())
    return kw


def main():
    kw = load_keywords()
    cats = collections.OrderedDict()
    group = sub = None
    total = matched = 0

    for line in (HERE / 'emoji-test.txt').read_text(encoding='utf-8').splitlines():
        if line.startswith('# group:'):
            group = line.split(':', 1)[1].strip()
            continue
        if line.startswith('# subgroup:'):
            sub = line.split(':', 1)[1].strip()
            continue
        if not line or line.startswith('#'):
            continue
        m = LINE_RE.match(line)
        if not m:
            continue
        _, status, ch, name = m.groups()
        # Only fully-qualified sequences render reliably. Components are not
        # standalone emoji, and skin-tone variants would multiply the set ~5x
        # for no search benefit.
        if status != 'fully-qualified' or group == 'Component':
            continue
        if any(c in ch for c in SKIN_TONES):
            continue
        total += 1

        words = set()
        words.update(name.lower().replace(':', ' ').replace(',', ' ').replace('-', ' ').split())
        words.update(sub.replace('-', ' ').lower().split())
        syn = kw.get(ch) or kw.get(ch.replace('️', ''))
        if syn:
            matched += 1
            for s in syn:
                words.update(s.split())

        cats.setdefault(group, []).append([ch, name, ' '.join(sorted(words))])

    out = [{'name': SHORT.get(g, g), 'icon': ICONS.get(g, 'emoji-symbols-symbolic'),
            'emojis': v} for g, v in cats.items()]

    OUT.write_text(
        "// Generated by tools/generate-emoji-data.py - do not edit by hand.\n"
        "// Unicode CLDR emoji-test.txt v15.1 + CLDR 45 annotations.\n"
        "// Format: [glyph, displayName, searchKeywords]\n"
        "export const EMOJI_CATEGORIES = "
        + json.dumps(out, ensure_ascii=False, separators=(',', ':')) + ";\n",
        encoding='utf-8')

    print(f"{total} emoji, {matched} with CLDR synonyms "
          f"({matched * 100 // total}%) -> {OUT.name}")


if __name__ == '__main__':
    main()
